package com.qixiu.newoulingzhu.constant;

/**
 * Created by Administrator on 2017/6/28 0028.
 */

public interface IntentRequestCodeConstant {
    //进入网页发布界面请求码
    int TORELEASE_REQUESTCODE = 110;
    //进入网页发布界面结果码
    int TORELEASE_RESULTCODE = 110011;

    int TOEVENTAPPLY_REQUESTCODE = 120;
    int TOEVENTAPPLY_RESULTCODE = 120021;

    int TONATIVEOWNER_RELEASE_REQUESTCODE = 111;
    int TONATIVEOWNER_RELEASE_RESULTCODE = 111111;

    int TONATIVEANSWER_RELEASE_REQUESTCODE = 112;
    int TONATIVEANSWER_RELEASE_RESULTCODE = 112211;

    int RELEASE_TOAUTHENTICATION_REQUESTCODE = 119;
    int RELEASE_TOAUTHENTICATION_RESULTCODE = 119911;
    int GOODDETAIL_TO_EVALUATE_REQUESTCODE = 113;
    int GOODDETAIL_TO_EVALUATE_RESULTCODE = 113311;
    int REQUESTCODE_EDITSINGLE = 114;
    int RESULTCODE_EDITSINGLE_NICKNAME = 114411;
    int RESULTCODE_EDITSINGLE_TRUENAME = 115511;
    int RESULTCODE_EDITSINGLE_EMAIL = 116611;


    int REQUESTCODE_RESETPHONE = 117;
    int RESULTCODE_RESETPHONE = 117711;

    int REQUESTCODE_START_PROBLEMDETAIL = 118;
    int RESULTCODE_START_PROBLEMDETAIL = 118811;
    int REQUESTCODE_START_CHAT = 120;
    int RESULTCODE_START_CHAT = 120021;
    int REQUESTCODE_EMAIL = 121;
    int RESULTCODE_EMAIL = 121121;

}
